//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RH_VETE_SMPEntities : DbContext
    {
        public RH_VETE_SMPEntities()
            : base("name=RH_VETE_SMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CANTON> CANTON { get; set; }
        public virtual DbSet<CORREO> CORREO { get; set; }
        public virtual DbSet<CURRICULUM> CURRICULUM { get; set; }
        public virtual DbSet<DIRECCION> DIRECCION { get; set; }
        public virtual DbSet<DISTRITO> DISTRITO { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<EVALUACION> EVALUACION { get; set; }
        public virtual DbSet<FORMULARIO> FORMULARIO { get; set; }
        public virtual DbSet<GENERO> GENERO { get; set; }
        public virtual DbSet<HISTORICO_CAPACITACION> HISTORICO_CAPACITACION { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<PLANILLA> PLANILLA { get; set; }
        public virtual DbSet<PROVINCIA> PROVINCIA { get; set; }
        public virtual DbSet<PUESTO> PUESTO { get; set; }
        public virtual DbSet<REMUNERACION> REMUNERACION { get; set; }
        public virtual DbSet<REPORTE_HISTORIAL> REPORTE_HISTORIAL { get; set; }
        public virtual DbSet<SELECCION> SELECCION { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T_CAPACITACION> T_CAPACITACION { get; set; }
        public virtual DbSet<TELEFONO> TELEFONO { get; set; }
        public virtual DbSet<TIPO_CORREO> TIPO_CORREO { get; set; }
        public virtual DbSet<TIPO_TELEFONO> TIPO_TELEFONO { get; set; }
        public virtual DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public virtual DbSet<TURNO> TURNO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
