//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONA()
        {
            this.CORREO = new HashSet<CORREO>();
            this.CURRICULUM = new HashSet<CURRICULUM>();
            this.EMPLEADO = new HashSet<EMPLEADO>();
            this.EVALUACION = new HashSet<EVALUACION>();
            this.FORMULARIO = new HashSet<FORMULARIO>();
            this.HISTORICO_CAPACITACION = new HashSet<HISTORICO_CAPACITACION>();
            this.PLANILLA = new HashSet<PLANILLA>();
            this.REPORTE_HISTORIAL = new HashSet<REPORTE_HISTORIAL>();
            this.TELEFONO = new HashSet<TELEFONO>();
            this.USUARIO = new HashSet<USUARIO>();
        }

        [Display(Name = "Cédula")]
        public string CEDULA { get; set; }
        public string NOMBRE { get; set; }
        [Display(Name = "Apellido")]
        public string APELLIDO_1 { get; set; }
        [Display(Name = "Seguno Apellido")]
        public string APELLIDO_2 { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        [Display(Name = "Dirección")]
        public int ID_DIRECCION { get; set; }
        [Display(Name = "Genero")]
        public int ID_GENERO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORREO> CORREO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CURRICULUM> CURRICULUM { get; set; }
        public virtual DIRECCION DIRECCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVALUACION> EVALUACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMULARIO> FORMULARIO { get; set; }
        public virtual GENERO GENERO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORICO_CAPACITACION> HISTORICO_CAPACITACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANILLA> PLANILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTE_HISTORIAL> REPORTE_HISTORIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TELEFONO> TELEFONO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
