//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMUNERACION
    {
        public int ID_REMUNERACION { get; set; }
        public int ID_EMPLEADO { get; set; }
        public int ID_PUESTO { get; set; }
        public byte CALIFICACION { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PUESTO PUESTO { get; set; }
    }
}
