//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE_HISTORIAL
    {
        public int ID_REPORTE_HISTORIAL { get; set; }
        public string CEDULA { get; set; }
        public int ID_TURNO { get; set; }
        public System.DateTime HORA_ENTRADA { get; set; }
        public System.DateTime HORA_SALIDA { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual TURNO TURNO { get; set; }
    }
}
